### ISSUE TITLE
Permission to use dataset for mne-python development

### ISSUE THREAD

**Issue by scott-huberty** [LABSN-pubs/2016-JASA-pupil-deconv-methods#1]
Hi @drammock - one of the features I wanted to implement in mne-python during my GSoC (but haven't got around to) is a pupil deconvolution function. I don't have any eyetracking files suitable for pupil deconvolution - I am wondering if we can add one of the files from this repo to `mne.datasets.eyelink`, and use it for development (and a tutorial) of a deconvolution function?

**Comment by drammock** [comment]
that should be fine. Data are already anonymous, so feel free to go through the `data` directory and find a file that looks suitable. Looks like I never specified a license so we can go with whatever we use in MNE for data files (possibly BSD3, just like the code?)
