### ISSUE TITLE
Missing file in Repo

### ISSUE THREAD

**Issue by scott-huberty** [LABSN-pubs/2016-JASA-pupil-deconv-methods#2]
Hello, I am interested in locally re-running the data processing and figure generation scripts. After setting up an environment, `analyze-data.py` (and thus `fig-1.py`) run without errors. However `analyze-voc-data.py` does not run because the mat file `voc-data/orderMain.mat` doesn't exist in this repo:

https://github.com/LABSN-pubs/2016-JASA-pupil-deconv-methods/blob/055dfc6a5b239fa270fd61271bcce49285c243ef/analyze-voc-data.py#L31-L35

Do you by any chance still have this file hanging around? No worries if it has been lost to time, I know it has been nearly a decade..

**Comment by drammock** [comment]
I might. I'll look tomorrow

**Comment by scott-huberty** [comment]
Thanks @drammock 🙏
